name: Coverage Test

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  backend-coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies and check coverage of pytests
        # continue-on-error: true
        run: |
          # python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt --quiet
          python coverage_check.py