name: Coverage Test

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  backend-coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: (see HERE for errors) Check coverage of pytests
        run: |
          cd backend
          python coverage_check.py