name: Deploy Backend to Server

on:
  push:
    branches:
      - main
      - matthew-digitalocean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies for backend
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Deploy Backend Files
        run: |
          rsync -avz --exclude=frontend/ ./backend/ -e "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no" root@${{ secrets.DIGITALOCEAN_SERVER_IP }}:/root/backend/

      - name: Restart Gunicorn
        run: |
          ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_SERVER_IP }} "sudo systemctl restart gunicorn"

      #.
      - name: Clean up SSH Key
        run: |
          rm -f /tmp/deploy_key
