name: Frontend CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  frontend-build-and-test:
    name: Run-jtests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev jest typescript ts-jest @types/jest jest-environment-jsdom

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm test
